spring.application.name=07-Boot-Amazon-Product-Service-Mongo-DB

spring.data.mongodb.uri=mongodb+srv://asitkumarnayak630_db_user:LImpSC6BAdEo0Mgl@mycluster1.sbwhajk.mongodb.net/AmazonProducts?retryWrites=true&w=majority&appName=MyCluster1

server.port=8089