spring.application.name=08-01-eureka-server

server.port=8086
# add this to avoid eureka dont try to register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8086/eureka/
