spring.application.name=10-02-config-client
server.port=8081
<<<<<<< HEAD
message=Hello from Config Server
=======
message=Hello from Config Server
>>>>>>> e8c2dc109c52bc8074c3a84f4bada136d2243670
