server:
  port: 8082

spring:
  application:
    name: 11-04-payment-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/